# Generated by Django 4.0.6 on 2022-07-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_active_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('value', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='date_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_active_users', models.ManyToManyField(to='main.daily_active_user')),
            ],
        ),
        migrations.CreateModel(
            name='install',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('value', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='package_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=30)),
                ('app_name', models.CharField(max_length=30)),
                ('daily_wise_mertic', models.ManyToManyField(to='main.date_info')),
            ],
        ),
        migrations.CreateModel(
            name='rev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('value', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='table',
            name='phone',
        ),
        migrations.DeleteModel(
            name='phone',
        ),
        migrations.DeleteModel(
            name='table',
        ),
        migrations.AddField(
            model_name='date_info',
            name='installs',
            field=models.ManyToManyField(to='main.install'),
        ),
        migrations.AddField(
            model_name='date_info',
            name='revenue',
            field=models.ManyToManyField(to='main.rev'),
        ),
    ]
