# Generated by Django 4.0.6 on 2022-07-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_daily_active_user_date_info_install_package_info_rev_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package_info',
            name='daily_wise_mertic',
        ),
        migrations.AddField(
            model_name='package_info',
            name='date_wise_metrics',
            field=models.JSONField(null=True),
        ),
    ]
