# Generated by Django 4.0.6 on 2022-07-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_package_info_daily_wise_mertic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_info',
            name='package_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
