# Generated by Django 4.0.6 on 2022-07-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_package_info_package_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='daily_active_user',
            new_name='DailyActiveUser',
        ),
        migrations.RenameModel(
            old_name='date_info',
            new_name='DateInfo',
        ),
        migrations.RenameModel(
            old_name='package_info',
            new_name='PackageInfo',
        ),
    ]
