# Generated by Django 4.0.6 on 2022-07-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_daily_active_user_dailyactiveuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageinfo',
            name='package_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
