# Generated by Django 4.0.6 on 2022-07-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_packageinfo_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageinfo',
            name='app_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='packageinfo',
            name='package_id',
            field=models.CharField(max_length=50),
        ),
    ]
